/************************* 시퀀스 *************************/
DROP SEQUENCE RANKS_SEQ;
DROP SEQUENCE DEPARTMENTS_SEQ;
DROP SEQUENCE EMPLOYEES_SEQ;
DROP SEQUENCE ATTENDANCE_RECORD_SEQ;
DROP SEQUENCE COURSE_SEQ;
DROP SEQUENCE EVENT_SEQ;
DROP SEQUENCE CHATROOM_SEQ;
DROP SEQUENCE MESSAGE_SEQ;
DROP SEQUENCE CHATROOM_PARTICIPATE_SEQ;
DROP SEQUENCE NOTIFICATION_SEQ;
DROP SEQUENCE FOLDER_SEQ;
DROP SEQUENCE FILE_SEQ;
DROP SEQUENCE NOTI_POST_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE ANON_POST_SEQ;
DROP SEQUENCE REPORTS_SEQ;
DROP SEQUENCE REQUESTS_SEQ;
DROP SEQUENCE REQUEST_ATTACH_SEQ;
DROP SEQUENCE LEAVE_REQUEST_SEQ;
DROP SEQUENCE ANNUAL_LEAVES_SEQ;
DROP SEQUENCE ATTACH_SEQ;

CREATE SEQUENCE RANKS_SEQ NOCACHE;
CREATE SEQUENCE DEPARTMENTS_SEQ NOCACHE;
CREATE SEQUENCE EMPLOYEES_SEQ NOCACHE;
CREATE SEQUENCE ATTENDANCE_RECORD_SEQ NOCACHE;
CREATE SEQUENCE COURSE_SEQ NOCACHE;
CREATE SEQUENCE EVENT_SEQ NOCACHE;
CREATE SEQUENCE CHATROOM_SEQ NOCACHE;
CREATE SEQUENCE MESSAGE_SEQ NOCACHE;
CREATE SEQUENCE CHATROOM_PARTICIPATE_SEQ NOCACHE;
CREATE SEQUENCE NOTIFICATION_SEQ NOCACHE;
CREATE SEQUENCE FOLDER_SEQ NOCACHE;
CREATE SEQUENCE FILE_SEQ NOCACHE;
CREATE SEQUENCE NOTI_POST_SEQ NOCACHE;
CREATE SEQUENCE COMMENTS_SEQ NOCACHE;
CREATE SEQUENCE ANON_POST_SEQ NOCACHE;
CREATE SEQUENCE REPORTS_SEQ NOCACHE;
CREATE SEQUENCE REQUESTS_SEQ NOCACHE;
CREATE SEQUENCE REQUEST_ATTACH_SEQ NOCACHE;
CREATE SEQUENCE LEAVE_REQUEST_SEQ NOCACHE;
CREATE SEQUENCE ANNUAL_LEAVES_SEQ NOCACHE;
CREATE SEQUENCE ATTACH_SEQ NOCACHE;

/************************* 테이블 *************************/
DROP TABLE HOLIDAYS_T;
DROP TABLE ATTENDANCE_ADJUSTMENT_REQUEST_T;
DROP TABLE LEAVE_REQUEST_T;
DROP TABLE REQUEST_ATTACH_T;
DROP TABLE REQUESTS_T;
DROP TABLE FILE_T;
DROP TABLE FOLDER_T;
DROP TABLE REPORTS_T;
DROP TABLE LIKES_T;
DROP TABLE COMMENTS_T;
DROP TABLE NOTI_ATTACH_T;
DROP TABLE ANON_POST_T;
DROP TABLE NOTI_POST_T;
DROP TABLE LEAVE_USES_T;
DROP TABLE ANNUAL_LEAVES_T;
DROP TABLE ATTENDANCE_RECORDS_T;
DROP TABLE EVENTS_T;
DROP TABLE CONSULTATIONS_T;
DROP TABLE TEXTBOOKS_T;
DROP TABLE COURSE_ENROLLMENTS_T;
DROP TABLE COURSES_T;
DROP TABLE STUDENT_CONTACTS_T;
DROP TABLE NOTIFICATIONS_T;
DROP TABLE EMAIL_ATTACH_T;
DROP TABLE EMAILS_T;
DROP TABLE MESSAGE_T;
DROP TABLE CHATROOM_PARTICIPATE_T;
DROP TABLE CHATROOM_T;
DROP TABLE EMPLOYEES_T;
DROP TABLE RANKS_T;
DROP TABLE DEPARTMENTS_T;


CREATE TABLE DEPARTMENTS_T (
	DEPARTMENT_NO	    NUMBER		NOT NULL,
	DEPART_NAME  	    VARCHAR2(100 BYTE)		NOT NULL,
	PARENT_DEPART_NO	NUMBER		NULL
);

CREATE TABLE RANKS_T (
	RANK_NO	NUMBER		NOT NULL,
	RANK_TITLE      	VARCHAR2(100 BYTE)		NOT NULL
);

CREATE TABLE EMPLOYEES_T (
	EMPLOYEE_NO           	NUMBER		NOT NULL,
	NAME                	VARCHAR2(100 BYTE)		NOT NULL,
	EMAIL                 	VARCHAR2(100 BYTE)		NOT NULL,
	PHONE                  	VARCHAR2(20 BYTE)		NOT NULL,
	ADDRESS               	VARCHAR2(200 BYTE)		NULL,
	DEPARTMENT_NO          	NUMBER		NULL,
	RANK_NO                	NUMBER		NULL,
	PASSWORD            	VARCHAR2(100  BYTE)		NOT NULL,
	PROFILE_PICTURE_PATH	VARCHAR2(400  BYTE)		NULL,
	EMPLOYEE_STATUS     	NUMBER		NOT NULL,
	HIRE_DATE           	DATE		NULL,
	EXIT_DATE           	DATE		NULL
);

select * from EMPLOYEES_T;


CREATE TABLE NOTIFICATIONS_T (
	NOTIFICATION_NO 	  NUMBER		        NOT NULL,
	MESSAGE 	          VARCHAR2(300 BYTE)	NOT NULL,
    NOTIFICATION_TYPE     VARCHAR2(20 BYTE)     NULL,
    NOTIFIER_NO           NUMBER                NULL,
	NOTIFICATION_DATE	  TIMESTAMP		        NULL,
	SEEN_STATUS 	      NUMBER		        NULL,
	EMPLOYEE_NO 	      NUMBER		        NULL,
    CHATROOM_NO           NUMBER                NULL
);



CREATE TABLE EMAILS_T (
	EMAIL_NO        	NUMBER		        NOT NULL,
	EMAIL_TITLE     	VARCHAR2(200 BYTE)  NULL,
	EMAIL_CONTENT   	CLOB        		NULL,
	EMAIL_DATE      	DATE        		NULL,
	FROM_EMPLOYEE_NO	NUMBER      		NULL,
	TO_EMPLOYEE_NO  	NUMBER      		NULL,
	EMAIL_STATUS    	NUMBER      		NULL
);



CREATE TABLE COURSES_T (
	COURSE_NO   	NUMBER          		NOT NULL,
	TITLE         	VARCHAR2(200 BYTE)		NULL,
	DESCRIPTION 	VARCHAR2(500 BYTE)		NULL,
	START_DATE  	DATE            		NULL,
	END_DATE    	DATE            		NULL,
	COURSE_PLAN 	VARCHAR2(500 BYTE)		NULL,
	COURSE_STATE    NUMBER          		NULL,
	EMPLOYEE_NO 	NUMBER          		NULL
);

CREATE TABLE STUDENT_CONTACTS_T (
	CONTACT_NO	NUMBER          		NOT NULL,
	NAME    	VARCHAR2(100 BYTE)		NULL,
	EMAIL   	VARCHAR2(100 BYTE)		NULL,
	PHONE   	VARCHAR2(20 BYTE)		NULL,
	ADDRESS 	VARCHAR2(500 BYTE)		NULL
);


CREATE TABLE COURSE_ENROLLMENTS_T (
	ENROLLMENT_NO	NUMBER		NOT NULL,
	STUDENT_NO  	NUMBER		NULL,
	ENROLLMENT_DATE	DATE		NULL,
	COURSE_NO   	NUMBER		NULL,
	CONTACT_NO  	NUMBER		NOT NULL
);


CREATE TABLE TEXTBOOKS_T (
	TEXTBOOK_NO	NUMBER          		NOT NULL,
	TITLE      	VARCHAR2(200 BYTE)		NULL,
	AUTHOR  	VARCHAR2(100 BYTE)		NULL,
	COURSE_NO	NUMBER          		NULL
);



CREATE TABLE CONSULTATIONS_T (
	CONSULTATION_NO 	NUMBER          		NOT NULL,
	CONSULTATION_DATE	DATE            		NULL,
	START_TIME      	DATE            		NULL,
	END_TIME        	DATE            		NULL,
	BACKGROUND_COLOR	VARCHAR2(50 BYTE)		NULL,
	TEXT_COLOR      	VARCHAR2(50 BYTE)		NULL,
	NOTES           	VARCHAR2(500 BYTE)		NULL,
	CONTACT_NO      	NUMBER          		NOT NULL,
	COUNSELOR_NO    	NUMBER          		NOT NULL
);



CREATE TABLE EVENTS_T (
	EVENT_NO        	NUMBER          		NOT NULL,
	TITLE              	VARCHAR2(200 BYTE)		NULL,
	START_DATE      	DATE            		NULL,
	END_DATE        	DATE            		NULL,
	BACKGROUND_COLOR	VARCHAR2(50 BYTE)		NULL,
	TEXT_COLOR      	VARCHAR2(50  BYTE)		NULL,
	LOCATION        	VARCHAR2(200 BYTE)		NULL,
	ALL_DAY             NUMBER                  NULL,
	LAT                 VARCHAR2(200 BYTE)      NULL,
	LNG                 VARCHAR2(200 BYTE)      NULL,
	DESCRIPTION        	VARCHAR2(200 BYTE)		NULL,
	OWNER_NO        	NUMBER		            NOT NULL
);



CREATE TABLE ATTENDANCE_RECORDS_T (
	RECORD_NO	NUMBER		NOT NULL,
	RECORD_DATE	DATE		NOT NULL,
	TIME_IN 	DATE		NULL,
	TIME_OUT	DATE		NULL,
	STATUS  	NUMBER		NULL,
	EMPLOYEE_NO	NUMBER		NOT NULL
);



CREATE TABLE ANNUAL_LEAVES_T (
	LEAVE_NO    	NUMBER		NOT NULL,
	YEAR        	NUMBER		NULL,
	REMAIN_LEAVES	NUMBER		NULL,
	USED_LEAVES 	NUMBER		NULL,
	TOTAL_LEAVES	NUMBER		NULL,
	EMPLOYEE_NO 	NUMBER		NULL
);



CREATE TABLE LEAVE_USES_T (
	USE_NO  	NUMBER		NOT NULL,
	LEAVE_DATE	DATE		NULL,
	DURATION	NUMBER		NULL,
	LEAVE_NO	NUMBER		NULL
);



CREATE TABLE "ANON_POST_T" (
	POST_NO	    	NUMBER		        NOT NULL,
	TITLE	        VARCHAR2(200 BYTE)	NULL,
	CONTENT	    	CLOB		        NULL,
	POST_DATE	DATE		        NULL,
	AUTHOR_NO	NUMBER		        NULL,
	HIT           	NUMBER              	DEFAULT 0,
    	STATUS        	NUMBER              	NULL
);



CREATE TABLE LIKES_T (
	LIKE_NO 	NUMBER		NOT NULL,
	POST_NO 	NUMBER  	NULL,
	EMPLOYEE_NO	NUMBER		NULL
);


CREATE TABLE "COMMENTS_T" (
	COMMENT_NO	    NUMBER		        NOT NULL,
	CONTENT	            VARCHAR2(4000 BYTE)		NULL,
	COMMENT_DATE	    DATE		        NULL,
	COMMENT_STATUS	    NUMBER		        NULL,
	POST_NO	            NUMBER		        NULL,
	AUTHOR_NO	        NUMBER		        NOT NULL,
    NOTI_POST_NO	    NUMBER		        NULL,
    DEPTH               NUMBER             		NULL,
    GROUP_NO            NUMBER              	NULL
);



CREATE TABLE "REPORTS_T" (
	REPORT_NO	        NUMBER		        NOT NULL,
	POST_NO	        	NUMBER		        NULL,
	AUTHOR_NO	        NUMBER		        NOT NULL,
	REPORT_CATEGORY		NUMBER		        NOT NULL,
	DESCRIPTION	    	VARCHAR2(300 BYTE)	NULL,
	REPORT_DATE       	DATE	                NULL
);



CREATE TABLE CHATROOM_T (
	CHATROOM_NO 	        NUMBER		        NOT NULL,
	CHATROOM_TITLE  	    VARCHAR2(200 BYTE)	NOT NULL,
    CHATROOM_TYPE            VARCHAR2(15 BYTE)  NOT NULL,
	CHATROOM_CREATED_DATE	TIMESTAMP		    NOT NULL,
	CREATOR_NO  	        NUMBER		        NULL
);

CREATE TABLE MESSAGE_T (
	MESSAGE_NO  	  NUMBER		        NOT NULL,
    MESSAGE_TYPE      VARCHAR2(30 BYTE)     NOT NULL,
	MESSAGE_CONTENT   VARCHAR2(4000 BYTE)	NULL,
    ALL_READ          NUMBER                DEFAULT 0,
	SEND_DT	          TIMESTAMP		        NULL,
	CHATROOM_NO	      NUMBER		        NULL,
	SENDER_NO	      NUMBER		        NULL
);


CREATE TABLE FOLDER_T (
	FOLDER_NO   	        NUMBER		        NOT NULL,
	FOLDER_NAME 	        VARCHAR2(200 BYTE)	NOT NULL,
    FOLDER_CREATE_DT        TIMESTAMP           NOT NULL,
    FOLDER_UPLOAD_PATH      VARCHAR2(500 BYTE)  NOT NULL,
    PARENT_FOLDER_NO        NUMBER              NULL,
	OWNER_NO    	        NUMBER		        NOT NULL
);

CREATE TABLE FILE_T (
	FILE_NO         	NUMBER		        NOT NULL,
	FILE_UPLOAD_PATH    VARCHAR2(500 BYTE)	NULL,
	FILESYSTEM_NAME  	VARCHAR2(500 BYTE)	NULL,
	ORIGINAL_FILENAME	VARCHAR2(500 BYTE)	NULL,
	FILE_UPLOAD_DT      TIMESTAMP	        NULL,
	FOLDER_NO	        NUMBER		        NOT NULL,
	OWNER_NO	        NUMBER		        NOT NULL
);



CREATE TABLE CHATROOM_PARTICIPATE_T (
	CHATROOM_PARTICIPATE_NO	  NUMBER		NOT NULL,
	CHATROOM_NO	              NUMBER		NOT NULL,
	PARTICIPANT_NO	          NUMBER		NULL,
    PARTICIPATE_STATUS        NUMBER        NULL
);


CREATE TABLE REQUESTS_T (
	REQUEST_NO  	NUMBER		            NOT NULL,
	REQUEST_SORT	NUMBER		            NOT NULL,
	REQUEST_DATE	DATE		            NOT NULL,
	REASON       	VARCHAR2(300 BYTE)		NULL,
	REQUEST_STATUS	NUMBER		            NOT NULL,
	REJECT_REASON	VARCHAR2(300 BYTE)		NULL,
	PIC_NO      	NUMBER		            NOT NULL,
	EMPLOYEE_NO 	NUMBER		            NOT NULL
);



CREATE TABLE REQUEST_ATTACH_T (
	ATTACH_NO       	NUMBER          		NOT NULL,
	UPLOAD_PATH     	VARCHAR2(500 BYTE)		NULL,
	FILESYSTEM_NAME 	VARCHAR2(500 BYTE)		NULL,
	ORIGINAL_FILENAME	VARCHAR2(500 BYTE)		NULL,
	REQUEST_NO      	NUMBER          		NOT NULL,
    DOWNLOAD_COUNT      NUMBER
);



CREATE TABLE NOTI_POST_T (
	NOTI_POST_NO	NUMBER          		NOT NULL,
	TITLE       	VARCHAR2(200 BYTE)		NULL,
	CONTENT     	CLOB            		NULL,
	POST_DATE   	DATE            		NULL,
	AUTHOR_NO   	NUMBER          		NOT NULL
);



CREATE TABLE NOTI_ATTACH_T (
	DRIVE_ATTACH_NO   	NUMBER          		NOT NULL,
	UPLOAD_PATH     	VARCHAR2(500 BYTE)		NULL,
	FILESYSTEM_NAME 	VARCHAR2(500 BYTE)		NULL,
	ORIGINAL_FILENAME	VARCHAR2(500 BYTE)		NULL,
	UPLOAD_DATE     	DATE            		NULL,
	NOTI_POST_NO       	NUMBER          		NULL,
	POST_NO 	        NUMBER              	NULL 
);


CREATE TABLE EMAIL_ATTACH_T (
	ATTACH_NO       	NUMBER          		NOT NULL,
	UPLOAD_PATH     	VARCHAR2(500 BYTE)		NULL,
	FILESYSTEM_NAME 	VARCHAR2(500 BYTE)		NULL,
	ORIGINAL_FILENAME	VARCHAR2(500 BYTE)		NULL,
	EMAIL_NO           	NUMBER          		NULL
);

CREATE TABLE HOLIDAYS_T (
	HOLIDAY_NO      	NUMBER              	NOT NULL,
	TITLE           	VARCHAR2(200 BYTE)		NULL,
	START_DATE      	DATE            		NULL,
	END_DATE        	DATE            		NULL,
	BACKGROUND_COLOR	VARCHAR2(50 BYTE)		NULL,
	TEXT_COLOR      	VARCHAR2(50 BYTE)		NULL,
	DESCRIPTION     	VARCHAR2(200 BYTE)		NULL
);

CREATE TABLE LEAVE_REQUEST_T (
	REQUEST_NO	NUMBER          		NOT NULL,
	START_DATE	DATE            		NOT NULL,
	END_DATE	DATE            		NOT NULL,
	DURATION	NUMBER          		NOT NULL,
	LEAVE_TYPE	VARCHAR2(500 BYTE)		NOT NULL,
    NAME    	VARCHAR2(100 BYTE)		NOT NULL,
    DEPART_NAME	VARCHAR2(100 BYTE)		NOT NULL,
    RANK_TITLE	VARCHAR2(100 BYTE)		NOT NULL
);


CREATE TABLE ATTENDANCE_ADJUSTMENT_REQUEST_T (
	REQUEST_NO  	NUMBER		NOT NULL,
	ADJUSTMENT_DATE	DATE		NULL,
	TIME_IN     	DATE		NULL,
	TIME_OUT    	DATE		NULL
);

ALTER TABLE EMPLOYEES_T ADD CONSTRAINT PK_EMPLOYEES_T PRIMARY KEY (
	EMPLOYEE_NO
);

ALTER TABLE NOTIFICATIONS_T ADD CONSTRAINT PK_NOTIFICATIONS_T PRIMARY KEY (
	NOTIFICATION_NO
);

ALTER TABLE STUDENT_CONTACTS_T ADD CONSTRAINT PK_STUDENT_CONTACTS_T PRIMARY KEY (
	CONTACT_NO
);

ALTER TABLE EMAILS_T ADD CONSTRAINT PK_EMAILS_T PRIMARY KEY (
	EMAIL_NO
);

ALTER TABLE COURSES_T ADD CONSTRAINT PK_COURSES_T PRIMARY KEY (
	COURSE_NO
);

ALTER TABLE COURSE_ENROLLMENTS_T ADD CONSTRAINT PK_COURSE_ENROLLMENTS_T PRIMARY KEY (
	ENROLLMENT_NO
);

ALTER TABLE TEXTBOOKS_T ADD CONSTRAINT PK_TEXTBOOKS_T PRIMARY KEY (
	TEXTBOOK_NO
);

ALTER TABLE CONSULTATIONS_T ADD CONSTRAINT PK_CONSULTATIONS_T PRIMARY KEY (
	CONSULTATION_NO
);

ALTER TABLE EVENTS_T ADD CONSTRAINT PK_EVENTS_T PRIMARY KEY (
	EVENT_NO
);

ALTER TABLE ATTENDANCE_RECORDS_T ADD CONSTRAINT PK_ATTENDANCE_RECORDS_T PRIMARY KEY (
	RECORD_NO
);

ALTER TABLE ANNUAL_LEAVES_T ADD CONSTRAINT PK_ANNUAL_LEAVES_T PRIMARY KEY (
	LEAVE_NO
);

ALTER TABLE LEAVE_USES_T ADD CONSTRAINT PK_LEAVE_USES_T PRIMARY KEY (
	USE_NO
);

ALTER TABLE ANON_POST_T ADD CONSTRAINT PK_ANON_POST_T PRIMARY KEY (
	POST_NO
);

ALTER TABLE LIKES_T ADD CONSTRAINT PK_LIKES_T PRIMARY KEY (
	LIKE_NO
);

ALTER TABLE COMMENTS_T ADD CONSTRAINT PK_COMMENTS_T PRIMARY KEY (
	COMMENT_NO
);

ALTER TABLE REPORTS_T ADD CONSTRAINT PK_REPORTS_T PRIMARY KEY (
	REPORT_NO
);

ALTER TABLE CHATROOM_T ADD CONSTRAINT PK_CHATROOM_T PRIMARY KEY (
	CHATROOM_NO
);

ALTER TABLE MESSAGE_T ADD CONSTRAINT PK_MESSAGE_T PRIMARY KEY (
	MESSAGE_NO
);

ALTER TABLE FOLDER_T ADD CONSTRAINT PK_FOLDER_T PRIMARY KEY (
	FOLDER_NO
);

ALTER TABLE FILE_T ADD CONSTRAINT PK_FILE_T PRIMARY KEY (
	FILE_NO
);

ALTER TABLE CHATROOM_PARTICIPATE_T ADD CONSTRAINT PK_CHATROOM_PARTICIPATE_T PRIMARY KEY (
	CHATROOM_PARTICIPATE_NO
);

ALTER TABLE REQUESTS_T ADD CONSTRAINT PK_REQUESTS_T PRIMARY KEY (
	REQUEST_NO
);

ALTER TABLE REQUEST_ATTACH_T ADD CONSTRAINT PK_REQUEST_ATTACH_T PRIMARY KEY (
	ATTACH_NO
);

ALTER TABLE NOTI_POST_T ADD CONSTRAINT PK_NOTI_POST_T PRIMARY KEY (
	NOTI_POST_NO
);

ALTER TABLE NOTI_ATTACH_T ADD CONSTRAINT PK_NOTI_ATTACH_T PRIMARY KEY (
	DRIVE_ATTACH_NO
);

ALTER TABLE EMAIL_ATTACH_T ADD CONSTRAINT PK_EMAIL_ATTACH_T PRIMARY KEY (
	ATTACH_NO
);

ALTER TABLE HOLIDAYS_T ADD CONSTRAINT PK_HOLIDAYS_T PRIMARY KEY (
	HOLIDAY_NO
);

ALTER TABLE LEAVE_REQUEST_T ADD CONSTRAINT PK_LEAVE_REQUEST_T PRIMARY KEY (
	REQUEST_NO
);


ALTER TABLE ATTENDANCE_ADJUSTMENT_REQUEST_T ADD CONSTRAINT PK_ATTENDANCE_ADJUSTMENT_REQUEST_T PRIMARY KEY (
	REQUEST_NO
);

ALTER TABLE DEPARTMENTS_T ADD CONSTRAINT PK_DEPARTMENTS_T PRIMARY KEY (
	DEPARTMENT_NO
);

ALTER TABLE RANKS_T ADD CONSTRAINT PK_RANKS_T PRIMARY KEY (
	RANK_NO
);

ALTER TABLE EMPLOYEES_T ADD CONSTRAINT FK_DEPARTMENTS_T_TO_EMPLOYEES_T_1 FOREIGN KEY (
	DEPARTMENT_NO
)
REFERENCES DEPARTMENTS_T (
	DEPARTMENT_NO
);

ALTER TABLE EMPLOYEES_T ADD CONSTRAINT FK_RANKS_T_TO_EMPLOYEES_T_1 FOREIGN KEY (
	RANK_NO
)
REFERENCES RANKS_T (
	RANK_NO
);

ALTER TABLE NOTIFICATIONS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_NOTIFICATIONS_T_1 FOREIGN KEY (
	EMPLOYEE_NO
)

REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE NOTIFICATIONS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_NOTIFICATIONS_T_2 FOREIGN KEY (
	NOTIFIER_NO
)

REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE NOTIFICATIONS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_NOTIFICATIONS_T_3 FOREIGN KEY (
	CHATROOM_NO
)

REFERENCES CHATROOM_T (
	CHATROOM_NO
);

ALTER TABLE EMAILS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_EMAILS_T_1 FOREIGN KEY (
	FROM_EMPLOYEE_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE EMAILS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_EMAILS_T_2 FOREIGN KEY (
	TO_EMPLOYEE_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE COURSES_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_COURSES_T_1 FOREIGN KEY (
	EMPLOYEE_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE COURSE_ENROLLMENTS_T ADD CONSTRAINT FK_COURSES_T_TO_COURSE_ENROLLMENTS_T_1 FOREIGN KEY (
	COURSE_NO
)
REFERENCES COURSES_T (
	COURSE_NO
);

ALTER TABLE COURSE_ENROLLMENTS_T ADD CONSTRAINT FK_STUDENT_CONTACTS_T_TO_COURSE_ENROLLMENTS_T_1 FOREIGN KEY (
	CONTACT_NO
)
REFERENCES STUDENT_CONTACTS_T (
	CONTACT_NO
);

ALTER TABLE TEXTBOOKS_T ADD CONSTRAINT FK_COURSES_T_TO_TEXTBOOKS_T_1 FOREIGN KEY (
	COURSE_NO
)
REFERENCES COURSES_T (
	COURSE_NO
);

ALTER TABLE CONSULTATIONS_T ADD CONSTRAINT FK_STUDENT_CONTACTS_T_TO_CONSULTATIONS_T_1 FOREIGN KEY (
	CONTACT_NO
)
REFERENCES STUDENT_CONTACTS_T (
	CONTACT_NO
);

ALTER TABLE CONSULTATIONS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_CONSULTATIONS_T_1 FOREIGN KEY (
	COUNSELOR_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE EVENTS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_EVENTS_T_1 FOREIGN KEY (
	OWNER_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE ATTENDANCE_RECORDS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_ATTENDANCE_RECORDS_T_1 FOREIGN KEY (
	EMPLOYEE_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE ANNUAL_LEAVES_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_ANNUAL_LEAVES_T_1 FOREIGN KEY (
	EMPLOYEE_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE LEAVE_USES_T ADD CONSTRAINT FK_ANNUAL_LEAVES_T_TO_LEAVE_USES_T_1 FOREIGN KEY (
	LEAVE_NO
)
REFERENCES ANNUAL_LEAVES_T (
	LEAVE_NO
);

ALTER TABLE ANON_POST_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_ANON_POST_T_1 FOREIGN KEY (
	AUTHOR_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE LIKES_T ADD CONSTRAINT FK_ANON_POST_T_TO_LIKES_T_1 FOREIGN KEY (
	POST_NO
)
REFERENCES ANON_POST_T (
	POST_NO
);

ALTER TABLE LIKES_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_LIKES_T_1 FOREIGN KEY (
	EMPLOYEE_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE COMMENTS_T ADD CONSTRAINT FK_ANON_POST_T_TO_COMMENTS_T_1 FOREIGN KEY (
	POST_NO
)
REFERENCES ANON_POST_T (
	POST_NO
);

ALTER TABLE COMMENTS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_COMMENTS_T_1 FOREIGN KEY (
	AUTHOR_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE REPORTS_T ADD CONSTRAINT FK_ANON_POST_T_TO_REPORTS_T_1 FOREIGN KEY (
	POST_NO
)
REFERENCES ANON_POST_T (
	POST_NO
);

ALTER TABLE REPORTS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_REPORTS_T_1 FOREIGN KEY (
	AUTHOR_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE CHATROOM_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_CHATROOM_T_1 FOREIGN KEY (
	CREATOR_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE MESSAGE_T ADD CONSTRAINT FK_CHATROOM_T_TO_MESSAGE_T_1 FOREIGN KEY (
	CHATROOM_NO
)
REFERENCES CHATROOM_T (
	CHATROOM_NO
);

ALTER TABLE MESSAGE_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_MESSAGE_T_1 FOREIGN KEY (
	SENDER_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE FOLDER_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_FOLDER_T_1 FOREIGN KEY (
	OWNER_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE FILE_T ADD CONSTRAINT FK_FOLDER_T_TO_FILE_T_1 FOREIGN KEY (
	FOLDER_NO
)
REFERENCES FOLDER_T (
	FOLDER_NO
);

ALTER TABLE FILE_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_FILE_T_1 FOREIGN KEY (
	OWNER_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE CHATROOM_PARTICIPATE_T ADD CONSTRAINT FK_CHATROOM_T_TO_CHATROOM_PARTICIPATE_T_1 FOREIGN KEY (
	CHATROOM_NO
)
REFERENCES CHATROOM_T (
	CHATROOM_NO
);

ALTER TABLE CHATROOM_PARTICIPATE_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_CHATROOM_PARTICIPATE_T_1 FOREIGN KEY (
	PARTICIPANT_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE REQUESTS_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_REQUESTS_T_1 FOREIGN KEY (
	EMPLOYEE_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE REQUEST_ATTACH_T ADD CONSTRAINT FK_REQUESTS_T_TO_REQUEST_ATTACH_T_1 FOREIGN KEY (
	REQUEST_NO
)
REFERENCES REQUESTS_T (
	REQUEST_NO
);

ALTER TABLE NOTI_POST_T ADD CONSTRAINT FK_EMPLOYEES_T_TO_NOTI_POST_T_1 FOREIGN KEY (
	AUTHOR_NO
)
REFERENCES EMPLOYEES_T (
	EMPLOYEE_NO
);

ALTER TABLE NOTI_ATTACH_T ADD CONSTRAINT FK_NOTI_POST_T_TO_NOTI_ATTACH_T_1 FOREIGN KEY (
	NOTI_POST_NO
)
REFERENCES NOTI_POST_T (
	NOTI_POST_NO
);

ALTER TABLE NOTI_ATTACH_T ADD CONSTRAINT FK_ANON_POST_T_TO_NOTI_ATTACH_T_1 FOREIGN KEY (
	POST_NO
)
REFERENCES ANON_POST_T (
	POST_NO
);

ALTER TABLE EMAIL_ATTACH_T ADD CONSTRAINT FK_EMAILS_T_TO_EMAIL_ATTACH_T_1 FOREIGN KEY (
	EMAIL_NO
)
REFERENCES EMAILS_T (
	EMAIL_NO
);

ALTER TABLE LEAVE_REQUEST_T ADD CONSTRAINT FK_REQUESTS_T_TO_LEAVE_REQUEST_T_1 FOREIGN KEY (
	REQUEST_NO
)
REFERENCES REQUESTS_T (
	REQUEST_NO
);